apiVersion: v1
kind: Pod
metadata:
  name: genai-perf-client
spec:
  imagePullSecrets:
    - name: ngc-secret
  containers:

  - name: perf-client-container
    image: nvcr.io/nvidia/vllm:25.09-py3
    env:
      - name: HF_TOKEN
        value: "<HF_TOKEN>"
    command: ["/bin/sh", "-c"]
    args:
      - |
           pip install genai-perf && \
           genai-perf profile --endpoint-type completions -m "gemma2-9b-instruct-lora_vhf-squad-v1" --streaming --concurrency 1 --url  nim-gemma-2-9b-lora-service:8000 --tokenizer="google/gemma-2-9b-it" && \
           genai-perf profile --endpoint-type completions -m "google/gemma-2-9b-it" --streaming --concurrency 1 --url  nim-gemma-2-9b-lora-service:8000 --tokenizer="google/gemma-2-9b-it"
